In [ ]:
import numpy as np


## New Section
**Array Initialization**

Creating an One dimensional array

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Now Creating 2D and 3D arrays. 2D array creation is kind of easy. But In terms of 3D arrays, we need to consider the format below
np.array([ [ [1,2,3], [2,3,4] ], [ [ 3,4,5], [3,4,5] ] ] )

In [ ]:
b = np.array([[1,2,4], [3,4,5]])
c = np.array([[[1,2,4],[3,5,4]],[[4,5,3],[3,4,5]]])
print(b)
print(c)

[[1 2 4]
 [3 4 5]]
[[[1 2 4]
  [3 5 4]]

 [[4 5 3]
  [3 4 5]]]


Changing the Datatype, We can change the datatype by changing the dtype function value.

In [ ]:
d = np.array([3,4,5],dtype= float)
print(d)

[3. 4. 5.]


Creating array by using arange function. The function is like this
np.arnage(initial value, final value, difference)

In [ ]:
e = np.arange(1,11,2)
print(e)

[1 3 5 7 9]


Reshaping function. It basically gives the user to change the shape of the matrix.

In [ ]:
f = np.arange(16).reshape(4,4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


ones,zeros,random. These are some of the functions that initializes array. In terms of ones, it initializes all values as 1,
In terms of zeros, It will initialize all the matrix value as 0,
And in terms of random number it will initialize all the matrix value from 0 to 1

In [ ]:
g = np.zeros(3)
h = np.ones(5)
i = np.random.random(5)
print(g)
print(h)
print(i)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[64.65919818 57.31119479 60.97531815 84.23704085 26.14209858]


By using linear space. It creates equal spaces betweent the values of the given parameter.

In [ ]:
j = np.linspace(1,20,4)
print(j)

[ 1.          7.33333333 13.66666667 20.        ]


Creating Identity matrix. It creates the Identity matrix, means all the diagonal value of the entity will be 1, and all other entity will be 0.

In [ ]:
k = np.identity(5)
print(k)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# New Section
**Array Attributes**

Just creating 1D, 2D and 3D arrays.

In [ ]:
a1 = np.arange(10,dtype =np.int32)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


Dimension check. In simple terms, If we look at the outlook of the matrix, we can tell it.
If the matrix contains one third bracket at the beginning or at the end , then it is called one dimensional. If 2 then 2D, if 3 then 3D.


In [ ]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


Shape checking. Shape means how the matrix look like. Means how much **Row and Column** it contains

In [ ]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


Size Checker. In short, Size function returns how much **Entity** are there in the matrix.

In [ ]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


Itemsize. It returns how much **Bytes** the entities are occupaying in the **RAM** . If it occupies 32 bits then it will show **32/8 = 4**, if 64 then it will show 8 bytes.

In [ ]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


*Just printing the datatype*

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


**Changing the Data Type**

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

*Array Operation* 2 types, Scalar operation and Vector operation

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
print(a1*5)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [ ]:
print(a2 == 10)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [ ]:
#vector operation
print(a1 ** a2)

[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[47. 95. 83.]
 [43. 94. 67.]
 [60. 98. 39.]]


Row and column operation
If the operation is **ROW** based then axis = 1
If the operation is **COLUMN** based then axis = 0

In [ ]:
print(a1)
print(np.prod(a1,axis = 0))
print(np.prod(a1,axis = 1))

[[47. 95. 83.]
 [43. 94. 67.]
 [60. 98. 39.]]
[121260. 875140. 216879.]
[370595. 270814. 229320.]


**Matrix Multiplication**
np.dot

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(a1)
print(a2)
dot = np.dot(a1,a2)
print(dot)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


***INDEXING AND SLICING***

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
print(a2[1,0])

4


Quiz : extract 5 from a3

In [ ]:
#print(a3)
print(a3[1,0,1])

5


Extract 6 from the a3 matrix


In [ ]:
print(a3[1,1,0])

6


Extract 2,4 from the a1

In [ ]:
print(a1)
print(a1[2:5:2])

[0 1 2 3 4 5 6 7 8 9]
[2 4]


1    3
5    7  from matrix a2

In [ ]:
print(a2)
print(a2[0:2,1::2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 3]
 [5 7]]


1 3 9 11 extract from a2

In [ ]:
print(a2[0::2,1::2])

[[ 1  3]
 [ 9 11]]


Extract 4    7 from the a2 matrix

In [ ]:
print(a2)
print(a2[1,0::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4 7]


extract 0 1 2 3 from the a2 matrix

In [ ]:
print(a2[0])

[0 1 2 3]


extract 2 6 10 from a2

In [ ]:
print(a2[:,2])

[ 2  6 10]


5   6
9   10

In [ ]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


Generate 3D matrix first

In [ ]:
a3 = np.arange(0,27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(a3[0::2,0,0::2])

[[ 0  2]
 [18 20]]


In [ ]:
print(a3[2:,1:,1:])

[[[22 23]
  [25 26]]]


In [ ]:
print(a3[0,1,:])

[3 4 5]


Iterating

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Transpose matrix

In [ ]:
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
print(a2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)
c = np.hstack((a4,a5))
d =np.vstack((a4,a5))
print(c)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


spliting

In [ ]:
print(np.hsplit(c,2))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [ ]:
print(np.vsplit(d,2))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
